# Generated by Django 6.0.3 on 2026-04-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Til nomi')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Til kodi (ISO)')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField(verbose_name='Asl matn')),
                ('translated_text', models.TextField(verbose_name='Tarjima qilingan matn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('from_lang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_translations', to='main.language')),
                ('to_lang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_translations', to='main.language')),
            ],
        ),
    ]
