# Generated by Django 6.0.3 on 2026-04-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationhistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Tarjima tarixi'},
        ),
    ]
